#!/bin/sh

set -e

libvirt_aa_helper_path='/usr/lib/libvirt/virt-aa-helper-unhooked'
libvirt_aa_config_path='/etc/apparmor.d/libvirt'
libvirt_aa_rules_regex='^\s*"[^"]\+"\s\+\([rwalkm]\|[pPcCuUi]\{0,3\}x\)\+,\s*$'

opts=$(/usr/bin/getopt -n "virt-aa-helper-hook" -o acDrRdu:hf:F: --long add,create,delete,replace,remove,dryrun,uuid:,help,add-file:,append-file: -- "$@")

xml="$(/usr/bin/cat)"

printf '%s' "$xml" | "$libvirt_aa_helper_path" "$@"

unset run
unset dry
unset uid

eval set -- "$opts"

while true; do
  case "$1" in
    -c|--create|-r|--replace)
      run=1
      shift
      ;;
    -d|--dryrun)
      dry=1
      shift
      ;;
    -u|--uuid)
      uid="${2}"
      shift 2
      ;;
    -a|--add|-D|--delete|-R|--remove|-h|--help)
      shift
      ;;
    -f|--add-file|-F|--append-file)
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [ -n "$run" ] && [ -z "$dry" ] && [ -n "$uid" ]; then
  aa_file="${libvirt_aa_config_path}/${uid}.files"
  if [ -e "$aa_file" ]; then
    printf '%s' "$xml" \
    | "$libvirt_aa_helper_path" -d -r -u "$uid" 2>&1 \
    | /usr/bin/grep "$libvirt_aa_rules_regex" \
    | while IFS= read -r rule; do
        if ! /usr/bin/grep -Fxq "$rule" "$aa_file"; then
          printf '%s\n' "$rule" >> "$aa_file"
        fi
      done
  fi
fi
